-- Chèn dữ liệu vào bảng roles
INSERT INTO roles (id, name, description) VALUES (1, 'ROLE_ADMIN', 'Administrator role');

-- Chèn tài khoản hợp lệ vào bảng users
INSERT INTO users (id, role_id, email, password, full_name, phone_number, address, avatar) 
VALUES (1, 1, 'ninh2k4@gmail.com', '$2a$10$HMAGA2rTlUe8Pq9kQUZ7cuycqZGJdYKLJo185EmrtfmsCsg5Qjsvy', 'yeu bome', '4324234234234', 'Thai Binh', '1740839936706-Screenshot 2024-11-29 165026.png');

-- Tạo bảng session cho spring-session
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);